### ISSUE TITLE
用户模块（UserService）新增手机号注册功能

### ISSUE THREAD

**Issue by highkay** [sgtcloud/sgtcloud-console#11]
1.用手机号发送验证码短信
2.回填验证码校验手机号
3.用手机号作为用户名完成注册（密码用默认值，例如###SGTCLOUD_SMS###）
4.重新梳理各种注册途径的类型，作为用户实体的一个属性，例如普通（用户名密码），手机号，微信登录，游戏基地登录等

**Comment by peisy** [comment]
svn已提交！
